name: Atualizacao Execucao Orcamentaria

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # Roda todos os dias às 09:00 UTC (06:00 AM Brasil)

jobs:
  atualiza_base:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v3

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar dependencias do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Instalar pacotes necessarios
        run: |
          install.packages(c("readxl", "readr", "dplyr", "lubridate"))
        shell: Rscript {0}

      - name: Rodar script de atualizacao
        run: Rscript orcamento/atualiza_base.R

      - name: Commit e push se houver mudancas
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Dados atualizados automaticamente" || echo "Sem mudanças"
          git push
